### ISSUE TITLE
Switch to GitHub action

### ISSUE THREAD

**Issue by joeldenning** [single-spa/sync-fork-repo#2]
Running this as a GitHub action would be ideal, as it wouldn't rely on @guguji5's personal server

**Comment by guguji5** [comment]
Got it , I will try it this weekend.

**Comment by joeldenning** [comment]
@tiagostutz if you have interest in helping with this, that could be helpful. @guguji5 is trying to convert this repo to be usable as a github action within the single-spa.js.org repo. The purpose of the project is to sync commits across repos, for the various languages that we have documented.

Both of you are in the single-spa Slack workspace - feel free to message each other if you'd like to discuss it together.

**Comment by tiagostutz** [comment]
Hi @joeldenning !! Thanks for offering this issue, I'll check the project and help with.

@guguji5 after I have check the project and put it to run locally I'll ask you for the next steps. Ok?

**Comment by guguji5** [comment]
@tiagostutz Sure! thanks you in advance. Let me introduce some message about this repo. 

When there is new commit merged into master of the [https://github.com/single-spa/single-spa.js.org](https://github.com/single-spa/single-spa.js.org) , it need a job to sync to the translated repo( zh-hans, pt-pt and es ). this repo makes it. Now it is running in my private server which set a crontab task to execute a commond just like below:
`
cd /home/dc2-user/sync-fork-repo/
source ~/.bash_profile && node index.js
`

A small question is that the job need to pull and push code in several repos, so it have a write access, `node index.js` will read the single-spa-bot username and access_token of GITHUB in the `bash_profile`. If transferring to Github Action, we have ensured the access_token is hidden.

**Comment by guguji5** [comment]
hi @joeldenning , I have set up Github Action, it need a secret for the access to repo single-spa/single-spa.js.org and the translated repos. the name and secret have sent you with Slack, Could you help to add it follow [this link](https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#creating-encrypted-secrets-for-an-organization) ?

**Comment by joeldenning** [comment]
Done
